export const newsConstants = {
  GET_ARTICLES_REQUEST: 'GET_ARTICLES_REQUEST',
  GET_ARTICLES_SUCCESS: 'GET_ARTICLES_SUCCESS',
  GET_ARTICLES_FAILURE: 'GET_ARTICLES_FAILURE',

  ARTICLE_REQUEST: 'ARTICLE_REQUEST',
  ARTICLE_SUCCESS: 'ARTICLE_SUCCESS',
  ARTICLE_FAILURE: 'ARTICLE_FAILURE',
}